Repository cp-ss2019/decentralized-energy-trading, pull requests merged in 2019-05, with the labels that each got.

#27 Feature/utility contract
  .gitignore
  README.md
  contracts/ConvertLib.sol
  contracts/IUtility.sol
  contracts/MetaCoin.sol
  contracts/Mortal.sol
  contracts/Owned.sol
  contracts/README.md
  contracts/Utility.sol
  migrations/2_deploy_contracts.js
  package.json
  test/.eslintrc.json
  test/metacoin.js
  test/utility.test.js
  truffle-config.js
  yarn.lock
Labels: enhancement

#32 Native PoA Setup
  .gitignore
  package.json
  parity-authority/docker/.env
  parity-authority/docker/LICENSE
  parity-authority/docker/README.md
  parity-authority/docker/dashboard/ws_secret.json
  parity-authority/docker/docker-compose.yml
  parity-authority/docker/docker_authority/Dockerfile
  parity-authority/docker/monitor/app.json
  parity-authority/docker/parity/authorities/authority0.json
  parity-authority/docker/parity/authorities/authority0.pwd
  parity-authority/docker/parity/authorities/authority1.json
  parity-authority/docker/parity/authorities/authority1.pwd
  parity-authority/docker/parity/authorities/authority2.json
  parity-authority/docker/parity/authorities/authority2.pwd
  parity-authority/docker/parity/config/authority.toml
  parity-authority/docker/parity/config/chain.json
  parity-authority/docker/parity/config/member.toml
  parity-authority/docker/parity/keys/address_book.json
  parity-authority/docker/parity/keys/authority.json
  parity-authority/docker/parity/keys/dapps_history.json
  parity-authority/docker/parity/keys/master0.json
  parity-authority/docker/parity/node0.network.key
  parity-authority/docker/parity/node1.network.key
  parity-authority/docker/parity/node2.network.key
  parity-authority/native/README.md
  parity-authority/native/parity/config.json
  parity-authority/native/parity/node.pwds
  parity-authority/native/parity/node.toml
  parity-authority/native/setup_bootnode.sh
  parity-authority/native/setup_node.sh
  scripts/run_docker_parity_tests.sh
  scripts/run_native_parity_tests.sh
  test/contracts/utility.test.js
  test/parity-authority/docker.test.js
  test/parity-authority/native.test.js
  yarn.lock
Labels: infrastructure, tests

#35 Add tests for events and adjust description
  README.md
  contracts/README.md
  contracts/Utility.sol
  test/contracts/utility.test.js
Labels: tests

#36 Partly FIFS settlement (netting) and tests (still unstable)
  contracts/FifsUtility.sol
  contracts/IUtility.sol
  contracts/Utility.sol
  migrations/.eslintrc
  migrations/2_deploy_contracts.js
  test/fifsUtility.test.js
Labels: enhancement, tests

#48 Add `test-contracts` script for win32 and win64
  package.json
  test-contracts.bat
  yarn.lock
Labels: tests

#63 [UC] Split energy
  contracts/FifsUtility.sol
  contracts/Utility.sol
  test/contracts/utility.test.js
Labels: enhancement

#64 [UC] retrieveReward and deeds
  contracts/FifsUtility.sol
  contracts/IUtility.sol
  test/contracts/fifsUtility.test.js
Labels: enhancement

#66 [UC] Overflow protection for int256 in UC
  contracts/FifsUtility.sol
  contracts/Utility.sol
  test/contracts/utility.test.js
Labels: enhancement

#109 [UC] Fix bug for consecutive settlements
  contracts/README.md
  contracts/Utility.sol
  test/contracts/utility.test.js
Labels: bug

#111 [HHS] Endpoint `GET /household-stats`
  contracts/UtilityBase.sol
  household-server/index.js
  household-server/transaction-handler.js
Labels: enhancement

#117 [HHS] `GET /network stats`
  household-server/index.js
  household-server/transaction-handler.js
Labels: enhancement

#118 Fix findByID
  household-server/db-handler.js
Labels: quick-fix

#120 [HHS] Include address in getHousehold
  contracts/UtilityBase.sol
  household-server/transaction-handler.js
Labels: quick-fix

#123 Fix GET /deeds
  household-server/index.js
Labels: quick-fix

#131 [CI] Fix test-contracts
  contracts/Utility.sol
  contracts/UtilityBase.sol
  package.json
  test/contracts/utility.test.js
  test/contracts/utilityBase.test.js
Labels: quick-fix

#132 [MS] Fix cli flag for endpoint and energybalance
  mock-sensor/README.md
  mock-sensor/index.js
Labels: quick-fix
