Repository cp-ss2019/decentralized-energy-trading, pull requests merged in 2019-06, with the labels that each got.

#135 Update yarn dependencies
  package.json
  truffle-config.js
  yarn.lock
Labels: quick-fix

#133 [UC] Fix settle does not update produce and consume
  contracts/Utility.sol
  contracts/UtilityBase.sol
Labels: question, quick-fix

#134 [UC] Functionality for official utility
  contracts/Utility.sol
  contracts/UtilityBase.sol
  contracts/interfaces/IUtility.sol
  contracts/libraries/SignedMath.sol
  parity-authority/docker/parity/config/chain.json
  test/contracts/utility.test.js
Labels: enhancement
